import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs';
import ErrorBoundary from '@/components/ErrorBoundary';
import Notifications from '@/components/Notifications';
import { Toaster } from 'react-hot-toast';
import ClientComponentWrapper from '@/components/ClientComponentWrapper';

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{
      baseTheme: undefined,
      variables: {
        colorPrimary: '#000000',
      },
      elements: {
        formButtonPrimary: 'bg-black hover:bg-gray-800 text-sm normal-case',
      },
    }}>
      <html lang="ja">
        <body className={`${inter.variable} font-sans antialiased`}>
          <ErrorBoundary>
            <ClientComponentWrapper>
              <Notifications />
              <Toaster position="top-right" />
            </ClientComponentWrapper>
            <main className="min-h-screen bg-white">{children}</main>
          </ErrorBoundary>
        </body>
      </html>
    </ClerkProvider>
  );
}
